### ISSUE TITLE
rdx was overwriten in example gif

### ISSUE THREAD

**Issue by cothan** [Boyan-MILANOV/ropium#35] opened 2021-01-19 06:36 UTC
I think example GIF does a very good impression of the tool. 
However, in the discussion with my friends, we spot an error in the GIF, probably in the tool too, is the command 

`find [rdx+32]=rax`, where `rdx` was overwritten, which lead to unexpected location. 

Line 1, line 4 should be something else rather than `rdx`. 

![image](https://user-images.githubusercontent.com/9219016/104996551-10959f00-59f6-11eb-88f3-1bea8997e901.png)

I also tried to reproduce this in libc.so.2.27 but the tool hang forever at similar `find` query.

My ROPium version is v3.1

**Comment by Boyan-MILANOV** [comment] 2021-01-19 17:58
Hey ! 

Indeed there is an error in the GIF, `rdx` shouldn't be overwritten. The error was already fixed in the tool though, that is why you can't reproduce it.
If the current version hangs on the query it means that it can't find a matching ropchain (I still have to implement a proper Ctrl+C to stop the search when it takes to long ). 

I'll change the GIF and replace this query with a similar one, like `find [rdx+16] = rax`. 

Thank you for noticing the error ! :)

**Comment by Boyan-MILANOV** [comment] 2021-02-22 19:31
GIF updated

**Closed by Boyan-MILANOV** 2021-02-22 19:31 UTC
